const Project = [
  {
    id: 1,
    name: 'Movie Mania Entertainment',
    description: 'This is a front-end web application for checking Movie and Series updates. It shows the movies currently playing in theatre, popular movies and series suggestions with their descriptions and genre.',
    image: 'https://www.linkpicture.com/q/complete.png',
    technologies: 'React, Redux, CSS3',
    live: 'https://movie-mania-kasilia-creations.netlify.app/',
    source: 'https://github.com/David-Kasilia/portfolio-project-1',
  },
  {
    id: 2,
    name: 'Bookstore CMS',
    description: 'This is a MVP version of it that allows the user to: Display a list of books, Add a book, Remove a selected book.',
    image: 'https://www.linkpicture.com/q/ScreenShot-Tool-20230127134444.png',
    technologies: 'React, Redux, CSS3',
    live: 'https://bookstore-cms-kasilia-creations.netlify.app',
    source: 'https://github.com/David-Kasilia/bookstore-with-react',
  },
  {
    id: 3,
    name: 'Leaderboard',
    description: 'This is JavaScript project for the Leaderboard list app, using webpack and ES6 features, notably modules.',
    image: 'https://www.linkpicture.com/q/ScreenShot-Tool-20230202125640.png',
    technologies: 'HTML, CSS, JavaScript, Webpack',
    live: 'https://mortal-kombat-leaderboard.netlify.app/',
    source: 'https://github.com/David-Kasilia/Leaderboard-Project',
  },
  {
    id: 4,
    name: 'Budget APP',
    description: 'This is building a mobile web application where you can manage your budget: you have a list of transactions associated with a category, so that you can see how much money you spent and on what.',
    image: 'https://www.linkpicture.com/q/localhost-3000-BudgetAppRor-1.png',
    technologies: 'Ruby, Ruby On Rails, PostgreSQL',
    live: ' https://budget-app-5474.onrender.com',
    source: 'https://github.com/David-Kasilia/budget_app_ror',
  },
  {
    id: 5,
    name: 'Greetings',
    description: 'This is a full stacked website which fetches data from an RESTFul API and renders greetings to the front-end',
    image: 'https://www.linkpicture.com/q/ScreenShot-Tool-20230202131049.png',
    technologies: 'React, Redux Ruby On Rails, PostgreSQL',
    live: 'https://hello-app-react-kasiliacreations.netlify.app',
    frontend: 'https://github.com/David-Kasilia/hello-react-front-end',
    backend: 'https://github.com/David-Kasilia/hello-rails-backend',
  },
  {
    id: 6,
    name: '3D Website',
    description: 'This Website is about, 3D technology (three-dimensional). Built with HTML and CSS only',
    image: 'https://www.linkpicture.com/q/ScreenShot-Tool-20230127134430.png',
    technologies: 'HTML, CSS, JavaScript',
    live: 'https://3d-website-kasilia-creations.netlify.app',
    source: 'https://github.com/David-Kasilia/3d-website',
  },
  {
    id: 7,
    name: 'Metrics APP: Countries',
    description: 'This React capstone project is about building a mobile web application to check a list of metrics (numeric values) that you will create making use of React and Redux.',
    image: 'https://www.linkpicture.com/q/ScreenShot-Tool-20230202131507.png',
    technologies: 'React, Redux',
    live: 'https://metrics-countries-kasilia-creations.netlify.app/',
    source: 'https://github.com/David-Kasilia/metrics-webapp',
  },
  {
    id: 8,
    name: 'Mobile App Landing Page',
    description: 'HTML/CSS & JavaScript First Microverse Capstone Project. This is a website for a mobile application landing page built with HTML, CSS and JavaScript',
    image: 'https://user-images.githubusercontent.com/83514256/185428522-8e414c09-b4ec-43eb-a673-7e1eb161fdd3.PNG',
    technologies: 'HTML, CSS, JavaScript',
    live: 'https://www.google.com',
    source: 'https://github.com/David-Kasilia/Capstone-Project-App-Landing-page',
  },
  {
    id: 9,
    name: 'Lamborghini Website Figma',
    description: 'This is a clone of the Lamborghini website User Interface Built with Figma',
    image: 'https://www.linkpicture.com/q/Lamborghini-Clone-UI.png',
    technologies: 'Figma',
    live: 'https://www.figma.com/file/zJUWspmkSGkUIVe8VsCPf4/Lamborghini-Clone-UI?node-id=0%3A1&t=JAudJC4oZxZTRq84-1',
    source: 'https://www.figma.com/file/zJUWspmkSGkUIVe8VsCPf4/Lamborghini-Clone-UI?node-id=0%3A1&t=JAudJC4oZxZTRq84-1',
  },
  {
    id: 10,
    name: 'Sneakers Android Application',
    description: 'There are a number of sneakers. This is an Android Application that has a list of popular sneakers and their relevant prices. You can add your sneakers to your favourite list of sneakers in the app.',
    image: 'https://www.linkpicture.com/q/sfsfsffsdfsfsdfsd.png',
    technologies: 'Kotlin',
    live: 'https://github.com/David-Kasilia/Sneakers-Application',
    source: 'https://github.com/David-Kasilia/Sneakers-Application',
  },
];

export default Project;
